// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/trading/DashboardOrbit.tsx": () => import("../components/mockups/trading/DashboardOrbit.tsx"),
  "./components/mockups/trading/OrbitCommand.tsx": () => import("../components/mockups/trading/OrbitCommand.tsx")
};
